'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DNNStuff.InjectAnything

    Partial Public Class Settings

        '''<summary>
        '''lblInsertionPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInsertionPoint As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlInsertionPoint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlInsertionPoint As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSource As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSource As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divStandard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divStandard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblStandard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStandard As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlStandard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStandard As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFile As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblLinkFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkFile As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkLinkFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLinkFile As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblToken control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblToken As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cmdRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRefresh As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlToken control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlToken As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEnable As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDebug As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDebug As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
